services:
  php:
    image: drupal:11-fpm
    container_name: ocp_php
    volumes:
    - ./docroot/web/modules:/var/www/html/modules
    - ./docroot/web/profiles:/var/www/html/profiles
    - ./docroot/web/themes:/var/www/html/themes
    - ./docroot/web/sites:/var/www/html/sites
    - ./docroot/composer.json:/opt/drupal/composer.json
    - ./docroot/composer.lock:/opt/drupal/composer.lock
    restart: always
    depends_on:
      - postgres

  nginx:
    image: nginx:1.27
    container_name: ocp_nginx
    volumes:
      - ./infrastructure/enviroments/develop/conf/sites.conf:/etc/nginx/conf.d/default.conf
      - ./docroot/web:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      
  postgres:
    image: postgres:16
    container_name: ocp_postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
